<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-17T12:12:06 IST" name="Suite" finished-at="2025-04-17T12:14:48 IST" duration-ms="161674">
    <groups>
    </groups>
    <test started-at="2025-04-17T12:12:06 IST" name="Positive_SubmitOrderTest" finished-at="2025-04-17T12:14:14 IST" duration-ms="127756">
      <class name="tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:12:07 IST" name="launchApplication" finished-at="2025-04-17T12:12:20 IST" duration-ms="12962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:12:20 IST" name="SubmitOrder" data-provider="getData" finished-at="2025-04-17T12:12:43 IST" duration-ms="23602" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Uname=Snehal.Chougule04@gmail.com, Passwd=NewJob@1008, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:12:43 IST" name="teardown" finished-at="2025-04-17T12:12:52 IST" duration-ms="8404" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:12:52 IST" name="launchApplication" finished-at="2025-04-17T12:12:59 IST" duration-ms="7399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:12:59 IST" name="SubmitOrder" data-provider="getData" finished-at="2025-04-17T12:13:17 IST" duration-ms="17648" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Uname=Snehal.Chougule04@gmail.com, Passwd=NewJob@1008, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:13:17 IST" name="teardown" finished-at="2025-04-17T12:13:25 IST" duration-ms="8369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:13:25 IST" name="launchApplication" finished-at="2025-04-17T12:14:04 IST" duration-ms="39156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistory()[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:14:04 IST" name="OrderHistory" finished-at="2025-04-17T12:14:06 IST" depends-on-methods="tests.SubmitOrderTest.SubmitOrder" duration-ms="1364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistory -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.SubmitOrderTest@303cf2ba]" started-at="2025-04-17T12:14:06 IST" name="teardown" finished-at="2025-04-17T12:14:14 IST" duration-ms="8463" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.SubmitOrderTest -->
    </test> <!-- Positive_SubmitOrderTest -->
    <test started-at="2025-04-17T12:14:15 IST" name="Negative_ErrorValidationTest" finished-at="2025-04-17T12:14:48 IST" duration-ms="33430">
      <class name="tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.ErrorValidationTest@29d80d2b]" started-at="2025-04-17T12:14:15 IST" name="launchApplication" finished-at="2025-04-17T12:14:21 IST" duration-ms="5844" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="IncorrectUserName_SubmitOrder()[pri:0, instance:tests.ErrorValidationTest@29d80d2b]" started-at="2025-04-17T12:14:21 IST" name="IncorrectUserName_SubmitOrder" finished-at="2025-04-17T12:14:22 IST" duration-ms="1634" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidationTest.IncorrectUserName_SubmitOrder(ErrorValidationTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncorrectUserName_SubmitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.ErrorValidationTest@29d80d2b]" started-at="2025-04-17T12:14:22 IST" name="teardown" finished-at="2025-04-17T12:14:31 IST" duration-ms="8331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.ErrorValidationTest@29d80d2b]" started-at="2025-04-17T12:14:31 IST" name="launchApplication" finished-at="2025-04-17T12:14:39 IST" duration-ms="8137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="IncorrectUserName_SubmitOrder()[pri:0, instance:tests.ErrorValidationTest@29d80d2b]" started-at="2025-04-17T12:14:39 IST" name="IncorrectUserName_SubmitOrder" finished-at="2025-04-17T12:14:39 IST" duration-ms="572" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidationTest.IncorrectUserName_SubmitOrder(ErrorValidationTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncorrectUserName_SubmitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.ErrorValidationTest@29d80d2b]" started-at="2025-04-17T12:14:40 IST" name="teardown" finished-at="2025-04-17T12:14:48 IST" duration-ms="8416" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.ErrorValidationTest -->
    </test> <!-- Negative_ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
